### ISSUE TITLE
'vagrant up' failing: USB controller implementation not found

### ISSUE THREAD

**Issue by Muzietto** [acntech/vagrant-xubuntu-developer#1]
I am working on an Ubuntu 15.04 laptop with VirtualBox 5.1.4. I have downloaded your box from Atlas without apparent problems.

But now the command `vagrant up` for this box fails with error message "Implementation of USB 2.0 controller not found".

If I check the VM settings from the VirtualBox manager, I find two warnings for "invalid settings detected".
Both warnings are complaining about the absence of the VBox Extension Pack.

**However, the Extension Pack is installed on my laptop. Your other box ubuntu64-dev works perfectly.**

Is my analysis correct? Any idea about what may be going wrong?

Thank you for your attention.

**Comment by onlyteo** [comment]
The USB 2.0 error is indeed related to the VirtualBox Extension Pack. It must be installed. If you have it already then I'm not sure why you get the error.

**Comment by onlyteo** [comment]
The box is running correctly on Windows, OSX and Ubuntu.
The Extension Pack must be the same version as the VirtualBox itself.
The ubuntu-64-dev was not created with the Extension Pack.
